<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Component-ids die niet in de admin-picker staan (geen paginacomponent).
    | Blade-partials in excluded_discovered_basenames worden ook niet auto-ontdekt.
    */
    'excluded_component_ids' => [
        'website.features_card',
        // Gebruik de sectie "Tekstblok" (text_block) in de page builder; die heeft de WYSIWYG-editor.
        'website.text_block_section',
    ],
    'excluded_discovered_basenames' => [
        'features-card',
        'features-card-section',
        'text-block-section',
    ],

    /*
    |--------------------------------------------------------------------------
    | Front-end componenten (automatisch ontdekt door de applicatie).
    | Alleen aanpasbaar in code; niet via beheerpagina's.
    | id: unieke key (module.key), gebruikt in section_order als "component:module.key"
    | name: weergavenaam in admin
    | module_name: modulenaam voor groepering (bijv. "Nexa Skillmatching")
    | view: Blade-view pad (zonder .blade.php)
    | description: korte omschrijving
    */
    'components' => [
        [
            'id' => 'website.google_reviews',
            'name' => 'Google Reviews',
            'module_name' => 'Algemeen',
            'view' => 'frontend.website.components.google-reviews',
            'description' => 'Carousel met Google-reviews (Place ID en cache in Configuraties > Algemeen).',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'website.nexa_modules_overview',
            'name' => 'NEXA modules overzicht',
            'module_name' => 'Algemeen',
            'view' => 'frontend.website.components.nexa-modules-overview',
            'description' => 'Verkooppagina met NEXA Skillmatching, Taxi en Garage modules.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'website.screenshot_gallery',
            'name' => 'Screenshot-galerij',
            'module_name' => 'Algemeen',
            'view' => 'frontend.website.components.screenshot-gallery',
            'description' => 'Productafbeeldingen met bijschrift, optioneel telefoon- of portaalcrop.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'website.comparison_table',
            'name' => 'Voor- en nadelen',
            'module_name' => 'Algemeen',
            'view' => 'frontend.website.components.comparison-table',
            'description' => 'Twee geanimeerde blokken: nadelen en voordelen, met scroll-reveal en staggered items.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'website.pricing_packages',
            'name' => 'Prijs pakketten',
            'module_name' => 'Algemeen',
            'view' => 'frontend.website.components.pricing-packages',
            'description' => 'Maandabonnementen, website eenmalig en extra opties.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'website.email_template_section',
            'name' => 'Email Template Section',
            'module_name' => 'Algemeen',
            'view' => 'frontend.website.components.email-template-section',
            'description' => 'Herbruikbare e-mail template sectie voor website builder contentblokken.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'nexa.recente_vacatures',
            'name' => 'Recente Vacatures',
            'module_name' => 'Nexa Skillmatching',
            /** Koppeling aan rij modules.name (skillmatching), i.p.v. alleen weergavenaam. */
            'module_key' => 'skillmatching',
            'view' => 'frontend.website.components.recente-vacatures',
            'description' => 'Blok met recente vacatures (container-custom, grid van vacaturekaarten en link naar vacaturesoverzicht).',
        ],
        [
            'id' => 'taxi.tarieven',
            'name' => 'Nexa Taxi tarieven',
            'module_name' => 'Nexa Taxi',
            'module_key' => 'taxi',
            'view' => 'frontend.website.components.nexataxi-tarieven',
            'description' => 'Tarieven t/m 4 en 5 t/m 8 personen met voertuigfoto\'s en overige kosten.',
        ],
        [
            'id' => 'taxi.boekingsmodule',
            'name' => 'Nexa Taxi boekingsmodule',
            'module_name' => 'Nexa Taxi',
            'module_key' => 'taxi',
            'view' => 'frontend.website.components.nexataxi-boekingsmodule',
            'description' => 'Meerstaps boekingsmodule met bagage, aanbiedingen, reisgegevens en contactgegevens.',
            'disabled' => true,
        ],
        [
            'id' => 'taxi.boekingsmodule_v2',
            'name' => 'Nexa Taxi boekingsmodule v2',
            'module_name' => 'Nexa Taxi',
            'module_key' => 'taxi',
            'view' => 'frontend.website.components.nexataxi-boekingsmodule-v2',
            'description' => 'Boekingsmodule met formulier links en live routekaart rechts. Verstuurt alleen naar het taxibedrijf van deze website.',
        ],
        [
            'id' => 'taxi.algemene_boekingsmodule',
            'name' => 'Algemene boekingsmodule',
            'module_name' => 'Nexa Taxi',
            'module_key' => 'taxi',
            'view' => 'frontend.website.components.nexataxi-algemene-boekingsmodule',
            'description' => 'Kopie van boekingsmodule v2 voor NEXA Suite: live beschikbare taxi’s op de kaart en ritten naar de dichtstbijzijnde aangesloten tenants.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'landwind.faq',
            'name' => 'FAQ-accordion',
            'module_name' => 'Thema: Landwind',
            'theme_slug' => 'landwind',
            'theme_name' => 'Landwind',
            'view' => 'frontend.website.components.landwind-faq',
            'description' => 'Landwind: Flowbite-accordion met vragen en antwoorden. Sleepbaar op elke pagina, ook bij een ander thema.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'landwind.trusted_by',
            'name' => 'Trusted-by merken',
            'module_name' => 'Thema: Landwind',
            'theme_slug' => 'landwind',
            'theme_name' => 'Landwind',
            'view' => 'frontend.website.components.landwind-trusted-by',
            'description' => 'Landwind: rij met merknamen (“Used by”), geen Google-reviews of screenshot-galerij.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'play.team',
            'name' => 'Teamgrid',
            'module_name' => 'Thema: Play Tailwind',
            'theme_slug' => 'play-tailwind',
            'theme_name' => 'Play Tailwind',
            'view' => 'frontend.website.components.play-team',
            'description' => 'Play Tailwind: teamkaarten met initialen, naam en rol. Sleepbaar op elke pagina, ook bij een ander thema.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'play.video_spotlight',
            'name' => 'Video-spotlight',
            'module_name' => 'Thema: Play Tailwind',
            'theme_slug' => 'play-tailwind',
            'theme_name' => 'Play Tailwind',
            'view' => 'frontend.website.components.play-video-spotlight',
            'description' => 'Play Tailwind: breed videovenster met play-overlay en YouTube-URL. Geen hero of carousel.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'vue_material.elevated_cards',
            'name' => 'Elevated infokaarten',
            'module_name' => 'Thema: Vue Material Kit',
            'theme_slug' => 'vue-material-kit',
            'theme_name' => 'Vue Material Kit',
            'view' => 'frontend.website.components.vue-material-elevated-cards',
            'description' => 'Vue Material Kit: drie verhoogde kaarten met ronde icoon-chip. Anders dan Features of Cards ronde hoeken.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'vue_material.quote_cards',
            'name' => 'Quote-kaarten',
            'module_name' => 'Thema: Vue Material Kit',
            'theme_slug' => 'vue-material-kit',
            'theme_name' => 'Vue Material Kit',
            'view' => 'frontend.website.components.vue-material-quote-cards',
            'description' => 'Vue Material Kit: Material quote-kaarten met grote aanhalingstekens. Geen Google Reviews-carousel.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'landwind.feature_checklist',
            'name' => 'Screenshot + checklist',
            'module_name' => 'Thema: Landwind',
            'theme_slug' => 'landwind',
            'theme_name' => 'Landwind',
            'view' => 'frontend.website.components.landwind-feature-checklist',
            'description' => 'Landwind: screenshot links, vinklijst rechts. Geen Features-grid.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'landwind.stats_strip',
            'name' => 'Cijferstrip',
            'module_name' => 'Thema: Landwind',
            'theme_slug' => 'landwind',
            'theme_name' => 'Landwind',
            'view' => 'frontend.website.components.landwind-stats-strip',
            'description' => 'Landwind: vier cijfers op een rij met count-up, geen kaartgrid.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'play.about_overlap',
            'name' => 'About overlappende foto’s',
            'module_name' => 'Thema: Play Tailwind',
            'theme_slug' => 'play-tailwind',
            'theme_name' => 'Play Tailwind',
            'view' => 'frontend.website.components.play-about-overlap',
            'description' => 'Play Tailwind: twee gestapelde foto’s naast tekst. Geen hero.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'play.blog_preview',
            'name' => 'Blog-preview',
            'module_name' => 'Thema: Play Tailwind',
            'theme_slug' => 'play-tailwind',
            'theme_name' => 'Play Tailwind',
            'view' => 'frontend.website.components.play-blog-preview',
            'description' => 'Play Tailwind: drie blogkaarten met foto, datum en excerpt.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'play.contact_split',
            'name' => 'Contact split',
            'module_name' => 'Thema: Play Tailwind',
            'theme_slug' => 'play-tailwind',
            'theme_name' => 'Play Tailwind',
            'view' => 'frontend.website.components.play-contact-split',
            'description' => 'Play Tailwind: contactgegevens links, berichtformulier rechts.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'vue_material.stats_counters',
            'name' => 'Stats count-up',
            'module_name' => 'Thema: Vue Material Kit',
            'theme_slug' => 'vue-material-kit',
            'theme_name' => 'Vue Material Kit',
            'view' => 'frontend.website.components.vue-material-stats-counters',
            'description' => 'Vue Material Kit: vier Material-tegels met geanimeerde tellers.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'vue_material.info_pills',
            'name' => 'Info-pills',
            'module_name' => 'Thema: Vue Material Kit',
            'theme_slug' => 'vue-material-kit',
            'theme_name' => 'Vue Material Kit',
            'view' => 'frontend.website.components.vue-material-info-pills',
            'description' => 'Vue Material Kit: filled tabs die panelen wisselen. Geen FAQ-accordion.',
            'available_on_all_pages' => true,
        ],
        [
            'id' => 'vue_material.author_header',
            'name' => 'Auteurheader',
            'module_name' => 'Thema: Vue Material Kit',
            'theme_slug' => 'vue-material-kit',
            'theme_name' => 'Vue Material Kit',
            'view' => 'frontend.website.components.vue-material-author-header',
            'description' => 'Vue Material Kit: profielheader met avatar, bio en socials.',
            'available_on_all_pages' => true,
        ],
    ],
];
