<?php

return [
    'from_name' => 'NEXA Suite',
    'contact_email' => 'info@nexasuite.nl',
    'max_send_per_run' => 80,
    'max_discover_per_run' => 300,
    'discover_timeout_seconds' => 120,
    'province_cities' => [
        'Drenthe' => 'Assen',
        'Flevoland' => 'Almere',
        'Friesland' => 'Leeuwarden',
        'Gelderland' => 'Arnhem',
        'Groningen' => 'Groningen',
        'Limburg' => 'Maastricht',
        'Noord-Brabant' => 'Eindhoven',
        'Noord-Holland' => 'Amsterdam',
        'Overijssel' => 'Zwolle',
        'Utrecht' => 'Utrecht',
        'Zeeland' => 'Middelburg',
        'Zuid-Holland' => 'Rotterdam',
    ],
    'provinces' => [
        'Drenthe' => 'Drenthe',
        'Flevoland' => 'Flevoland',
        'Friesland' => 'Friesland',
        'Gelderland' => 'Gelderland',
        'Groningen' => 'Groningen',
        'Limburg' => 'Limburg',
        'Noord-Brabant' => 'Noord-Brabant',
        'Noord-Holland' => 'Noord-Holland',
        'Overijssel' => 'Overijssel',
        'Utrecht' => 'Utrecht',
        'Zeeland' => 'Zeeland',
        'Zuid-Holland' => 'Zuid-Holland',
    ],
    'stock_images' => [
        'hero' => 'assets/marketing/images/hero-nexa-platform.png',
        'booking' => 'assets/marketing/images/feature-taxi-booking.png',
        'driver' => 'assets/marketing/images/feature-chauffeur-app.png',
        'contract' => 'assets/marketing/images/feature-contract-portal.png',
        'website' => 'assets/marketing/images/feature-website-builder.png',
        'planning' => 'assets/marketing/images/feature-contract-planning.png',
    ],
];
