version: "3.9"

# Development Docker Compose
# Voor lokale development met eigen database

services:
  # Lokale PostgreSQL voor development
  db:
    image: postgres:16-alpine
    container_name: nexa_db_dev
    environment:
      POSTGRES_USER: nexa
      POSTGRES_PASSWORD: nexa
      POSTGRES_DB: nexa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Backend development server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexa_backend_dev
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: nexa
      DB_USERNAME: nexa
      DB_PASSWORD: nexa
      # N8N - Development kan externe service gebruiken of mock
      N8N_URL: ${N8N_URL:-https://n8n.tosun.nl}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_EMAIL: ${N8N_EMAIL:-}
      N8N_PASSWORD: ${N8N_PASSWORD:-}
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:

# Note: N8N wordt niet lokaal gedraaid in development
# Gebruik de externe N8N service op https://n8n.tosun.nl


