version: "3.9"

# Development Docker Compose
# Gebruikt externe database op mdb.tosun.nl

services:
  # Backend development server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexa_backend
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      
      # Database - Externe PostgreSQL (mdb.tosun.nl)
      DB_CONNECTION: pgsql
      DB_HOST: mdb.tosun.nl
      DB_PORT: 5432
      DB_DATABASE: nexa
      DB_USERNAME: mtosun
      DB_PASSWORD: ${DB_PASSWORD}
      
      # N8N - Externe service
      N8N_URL: ${N8N_URL:-https://n8n.tosun.nl}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_EMAIL: ${N8N_EMAIL:-m.tosun@mebura.nl}
      N8N_PASSWORD: ${N8N_PASSWORD}
    volumes:
      - ./backend:/var/www/html
    restart: unless-stopped
    network_mode: "host"  # Voor toegang tot externe resources

# Geen volumes meer nodig (geen lokale database)

# Note: 
# - Database draait op mdb.tosun.nl (192.168.178.249)
# - N8N draait op https://n8n.tosun.nl
# - Geen lokale containers voor database of N8N


