<?php

namespace Database\Seeders;

use App\Models\StageType;
use Illuminate\Database\Seeder;

class StageTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stageTypes = [
            [
                'key' => 'SOURCE',
                'default_label' => 'Binnengekomen',
                'category' => 'source',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => false,
                'required_artifacts' => [],
                'optional_artifacts' => ['source', 'notes'],
                'outcomes' => [],
                'allowed_next_stage_types' => ['SCREENING', 'INTAKE', 'REJECTION'],
                'sort_order' => 10,
            ],
            [
                'key' => 'SCREENING',
                'default_label' => 'CV screening',
                'category' => 'screening',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => [],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL'],
                'allowed_next_stage_types' => ['INTAKE', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 20,
            ],
            [
                'key' => 'INTAKE',
                'default_label' => 'Intake gesprek',
                'category' => 'interview',
                'typical_duration_minutes' => 30,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => [],
                'optional_artifacts' => ['notes', 'rating', 'next_steps'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TEAM_INTERVIEW', 'TECHNICAL_INTERVIEW', 'TAKE_HOME_ASSIGNMENT', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 30,
            ],
            [
                'key' => 'RECRUITER_CALL',
                'default_label' => 'Recruiter gesprek',
                'category' => 'interview',
                'typical_duration_minutes' => 30,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => [],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['INTAKE', 'HIRING_MANAGER_CALL', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 25,
            ],
            [
                'key' => 'HIRING_MANAGER_CALL',
                'default_label' => 'Hiring manager gesprek',
                'category' => 'interview',
                'typical_duration_minutes' => 45,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => [],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TEAM_INTERVIEW', 'TECHNICAL_INTERVIEW', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 35,
            ],
            [
                'key' => 'TEAM_INTERVIEW',
                'default_label' => 'Vervolggesprek (team)',
                'category' => 'interview',
                'typical_duration_minutes' => 60,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => ['interviewers'],
                'optional_artifacts' => ['scorecard', 'notes'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TECHNICAL_INTERVIEW', 'CULTURE_INTERVIEW', 'REFERENCE_CHECK', 'SALARY_NEGOTIATION', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 40,
            ],
            [
                'key' => 'TECHNICAL_INTERVIEW',
                'default_label' => 'Technisch gesprek',
                'category' => 'interview',
                'typical_duration_minutes' => 60,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => ['interviewers'],
                'optional_artifacts' => ['scorecard', 'notes', 'technical_assessment'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TAKE_HOME_ASSIGNMENT', 'LIVE_CODING', 'TEAM_INTERVIEW', 'CULTURE_INTERVIEW', 'SALARY_NEGOTIATION', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 45,
            ],
            [
                'key' => 'TAKE_HOME_ASSIGNMENT',
                'default_label' => 'Take-home opdracht',
                'category' => 'assessment',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => ['assignment_url', 'deadline'],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TECHNICAL_INTERVIEW', 'LIVE_CODING', 'TEAM_INTERVIEW', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 50,
            ],
            [
                'key' => 'LIVE_CODING',
                'default_label' => 'Live coding sessie',
                'category' => 'assessment',
                'typical_duration_minutes' => 90,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => ['interviewers'],
                'optional_artifacts' => ['scorecard', 'notes'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TECHNICAL_INTERVIEW', 'TEAM_INTERVIEW', 'CULTURE_INTERVIEW', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 55,
            ],
            [
                'key' => 'CASE_INTERVIEW',
                'default_label' => 'Case interview',
                'category' => 'interview',
                'typical_duration_minutes' => 60,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => ['interviewers'],
                'optional_artifacts' => ['scorecard', 'notes'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TEAM_INTERVIEW', 'CULTURE_INTERVIEW', 'SALARY_NEGOTIATION', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 60,
            ],
            [
                'key' => 'ASSESSMENT',
                'default_label' => 'Assessment',
                'category' => 'assessment',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => ['assessment_url'],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['TECHNICAL_INTERVIEW', 'TEAM_INTERVIEW', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 65,
            ],
            [
                'key' => 'CULTURE_INTERVIEW',
                'default_label' => 'Cultuur gesprek',
                'category' => 'interview',
                'typical_duration_minutes' => 45,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => ['interviewers'],
                'optional_artifacts' => ['scorecard', 'notes'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['REFERENCE_CHECK', 'SALARY_NEGOTIATION', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 70,
            ],
            [
                'key' => 'REFERENCE_CHECK',
                'default_label' => 'Referentiecheck',
                'category' => 'check',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => ['references'],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['BACKGROUND_CHECK', 'SALARY_NEGOTIATION', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 75,
            ],
            [
                'key' => 'BACKGROUND_CHECK',
                'default_label' => 'Achtergrondcheck',
                'category' => 'check',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => [],
                'optional_artifacts' => ['notes', 'rating'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['SALARY_NEGOTIATION', 'OFFER', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 80,
            ],
            [
                'key' => 'SALARY_NEGOTIATION',
                'default_label' => 'Salarisgesprek',
                'category' => 'offer',
                'typical_duration_minutes' => 30,
                'can_schedule' => true,
                'can_collect_feedback' => true,
                'required_artifacts' => ['salary_range'],
                'optional_artifacts' => ['benefits', 'contract_type', 'start_date'],
                'outcomes' => ['PASS', 'FAIL', 'ON_HOLD'],
                'allowed_next_stage_types' => ['OFFER', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 85,
            ],
            [
                'key' => 'OFFER',
                'default_label' => 'Aanbod',
                'category' => 'offer',
                'typical_duration_minutes' => 0,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => ['offer_document'],
                'optional_artifacts' => ['deadline', 'counter_offer'],
                'outcomes' => ['ACCEPTED', 'DECLINED', 'ON_HOLD'],
                'allowed_next_stage_types' => ['SIGNING', 'REJECTION', 'ON_HOLD'],
                'sort_order' => 90,
            ],
            [
                'key' => 'SIGNING',
                'default_label' => 'Ondertekening',
                'category' => 'offer',
                'typical_duration_minutes' => 0,
                'can_schedule' => false,
                'can_collect_feedback' => true,
                'required_artifacts' => ['contract_document'],
                'optional_artifacts' => ['notes'],
                'outcomes' => ['COMPLETED'],
                'allowed_next_stage_types' => [],
                'sort_order' => 95,
            ],
            [
                'key' => 'REJECTION',
                'default_label' => 'Afgewezen',
                'category' => 'terminal',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => false,
                'required_artifacts' => [],
                'optional_artifacts' => ['reason', 'notes'],
                'outcomes' => [],
                'allowed_next_stage_types' => [],
                'sort_order' => 100,
            ],
            [
                'key' => 'WITHDRAWN',
                'default_label' => 'Ingetrokken',
                'category' => 'terminal',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => false,
                'required_artifacts' => [],
                'optional_artifacts' => ['reason', 'notes'],
                'outcomes' => [],
                'allowed_next_stage_types' => [],
                'sort_order' => 101,
            ],
            [
                'key' => 'ON_HOLD',
                'default_label' => 'Op pauze',
                'category' => 'pause',
                'typical_duration_minutes' => null,
                'can_schedule' => false,
                'can_collect_feedback' => false,
                'required_artifacts' => [],
                'optional_artifacts' => ['reason', 'notes'],
                'outcomes' => [],
                'allowed_next_stage_types' => ['INTAKE', 'TEAM_INTERVIEW', 'TECHNICAL_INTERVIEW', 'REJECTION', 'WITHDRAWN'],
                'sort_order' => 102,
            ],
        ];

        foreach ($stageTypes as $stageType) {
            StageType::updateOrCreate(
                ['key' => $stageType['key']],
                $stageType
            );
        }
    }
}
